version: "3"

volumes:
  se_storage:
  cache_storage:

networks:
  default:

services:
  se:
    image: storm2/ngx-voms
    hostname: nginx-voms
    dns_search: example
    ports:
      - "8443:443"
    volumes:
      - ./assets/trust-anchors:/etc/pki
      - ./assets/se/certs:/certs
      - ./assets/se/nginx/nginx_voms_se.conf:/home/build/local/openresty/nginx/conf/nginx.conf
      - se_storage:/data/nginx/www

    networks:
      default:
        aliases:
          - nginx-voms.example
  cache:
    image: storm2/ngx-voms
    hostname: cache
    dns_search: example
    ports:
      - "9443:443"
    volumes:
      - ./assets/trust-anchors:/etc/pki
      - ./assets/cache/certs:/certs
      - ./assets/usercerts:/usercerts
      - ./assets/vomsdir:/vomsdir
      - ./assets/cache/nginx/nginx_voms_cache.conf:/home/build/local/openresty/nginx/conf/nginx.conf
      - cache_storage:/data/nginx/cache
    depends_on:
      - se

    networks:
      default:
        aliases:
          - cache.example
    links:
       - se
  client-voms:
    user: test
    image: storm2/clients
    hostname: client-voms
    environment:
      TZ: Europe/Rome

    depends_on:
      - se

    networks:
      default:

    volumes:
      - ./assets/trust-anchors:/etc/pki
      - ./assets/usercerts:/certs
      - ./assets/vomsdir:/vomsdir
      - ./assets/vomses:/home/test/.voms/vomses
      - se_storage:/data/nginx/www
      - cache_storage:/data/nginx/cache

    entrypoint: sleep infinity
