version: "3.5"

volumes:
  saconfig:
  mapfilesconfig:
  webdav_hostcert:
  webdav_certs:
  vomsdir:
  storage:

services:
  storm_webdav_setup:
    build:
      context: ../../
      dockerfile: storage/storm-webdav/assets/docker/setup/Dockerfile
    dns_search: 8.8.8.8
    volumes:
      - ./assets/scripts:/scripts:ro
      - ./assets/storm-webdav/etc/storm/webdav/sa.d/:/sa.d:ro
      - ./assets/storm-webdav/etc/storm/webdav/vo-mapfiles.d/:/vo-mapfiles.d:ro
      - ./assets/vomsdir:/vomsdir:ro
      - ./assets/certs/digicert:/digicert
      - webdav_hostcert:/etc/grid-security/storm-webdav
      - webdav_certs:/etc/grid-security/certificates
      - vomsdir:/etc/grid-security/vomsdir
      - saconfig:/etc/storm/webdav/sa.d
      - mapfilesconfig:/etc/storm/webdav/vo-mapfiles.d

  storm_webdav_storage:
    image: italiangrid/storm-webdav-centos7:latest
    volumes:
      - webdav_hostcert:/etc/grid-security/storm-webdav
      - webdav_certs:/etc/grid-security/certificates
      - vomsdir:/etc/grid-security/vomsdir
      - saconfig:/etc/storm/webdav/sa.d
      - mapfilesconfig:/etc/storm/webdav/vo-mapfiles.d
      - ./assets/scripts:/scripts:ro
      - storage:/storage
    depends_on:
      - storm_webdav_setup
    entrypoint:
      - /scripts/init-storage.sh

  storm_webdav:
    hostname: ${HOSTNAME}
    build:
      context: ../../
      dockerfile: storage/storm-webdav/assets/docker/storm-webdav/Dockerfile
    environment:
      TZ: UTC
      STORM_WEBDAV_REQUIRE_CLIENT_CERT: "false"
      STORM_WEBDAV_HOSTNAME_0: ${HOSTNAME}
      STORM_WEBDAV_USE_CONSCRYPT: "true"
      STORM_WEBDAV_REQUIRE_CLIENT_CERT: "false"
      STORM_WEBDAV_HTTPS_PORT: 11443
      STORM_WEBDAV_HTTP_PORT: 11085
    dns_search: 127.0.0.11
    volumes:
      - ./assets/storm-webdav/etc/storm/webdav/config:/etc/storm/webdav/config:ro
      - ./assets/scripts/replace_iam_ip.sh:/home/storm/replace_iam_ip.sh
      - webdav_certs:/etc/grid-security/certificates
      - webdav_hostcert:/etc/grid-security/storm-webdav
      - saconfig:/etc/storm/webdav/sa.d
      - mapfilesconfig:/etc/storm/webdav/vo-mapfiles.d
      - vomsdir:/etc/grid-security/vomsdir
      - storage:/storage
    depends_on:
      - storm_webdav_storage
    ports:
      - "11443:11443"
      - "11085:11085"
    networks:
      default:
        aliases:
          - ${HOSTNAME}
