version: "3.5"

services:
  dynafed:
    hostname: ${HOSTNAME}
    dns_search: 127.0.0.11
    build:
      context: ../
      dockerfile: dynafed/assets/docker/Dockerfile
    environment:
      TZ: UTC
    volumes:
      - ./assets/conf.d/ssl.conf:/etc/httpd/conf.d/ssl.conf
      - ./assets/conf.d/httpd.conf:/etc/httpd/conf/httpd.conf
      - ./assets/conf.d/ugr.conf:/etc/ugr/ugr.conf
      - ./assets/conf.d/ugrdmlite.conf:/etc/ugr/ugrdmlite.conf
      - ./assets/conf.d/zlcgdm-ugr-dav.conf:/etc/httpd/conf.d/zlcgdm-ugr-dav.conf
      - ./assets/conf.d/endpoints.conf:/etc/ugr/conf.d/endpoints.conf
      - ./assets/scripts/test_gridmapfile.py:/root/test_gridmapfile.py
      - ./assets/conf.d/accessfile:/etc/grid-security/accessfile
      - ./assets/conf.d/grid-mapfile:/etc/grid-security/grid-mapfile
      - ./assets/vomsdir:/etc/grid-security/vomsdir
      - ./assets/scripts/register_client.sh:/register_client.sh
      - ./assets/scripts/oidc_get_token.sh:/oidc_get_token.sh
      - ./assets/scripts/oidc_expect.sh:/oidc_expect.sh
      - ./assets/oidc-agent/:/root/.oidc-agent/
      - ./assets/scripts/replace_iam_ip.sh:/replace_iam_ip.sh
    ports:
      - "10443:10443"
      - "1044:80"
    networks:
      default:
        aliases:
          - dynafed.local
    #depends_on:
      #- cache_1
      #- cache_2
