version: "3.5"

services:
  ui:
    build:
      context: .
      dockerfile: assets/docker/Dockerfile
    hostname: ${HOSTNAME}
    volumes:
      - ./assets/oidc-agent/:/home/storm/.oidc-agent/
    networks:
      default:
        aliases:
          - ui.example
